### PR TITLE
Modify approach to serving UI

### PR DESCRIPTION
**Pull request by jcheng5**
Instead of combining all of the UI objects into a single page that is
served to all of the windows, make the main UI a dynamic function that
knows what window it's in, and serves only the appropriate UI.

Also, dependencies no longer need to be provided explicitly. This was
only necessary before due to `paste`-ing of UI objects, which should
generally never be done because it causes dependency information to
be dropped on the floor. Instead, we compose our UI using tag objects
all the way up to the page level.

### CODE REVIEW

**Comment by delosh653** [comment]
Coincidentally, I fixed the dependencies problem today (by using tags) and pushed it, before I saw this, sorry!

I do like the idea of each page being separate -- that fixes the problem of certain tags being used. However, the URLs are no longer intuitively named (i.e., the url ends with ?Controller rather than ?mw_win=1). Can this be fixed?

**Comment by jcheng5** [comment]
It can certainly be fixed--I changed it to be numbers so that there would be no restriction on what the windows could be named. But you could accomplish the best of both worlds by calling `make.names()` on the window names (making sure that you don't end up with any duplicates, since `"Controller?"` and `"Controller!"` both normalize to `"Controller."`).

**Comment by delosh653** [comment]
I don't like the coercion of make.names(), at least, not without a warning. At the moment, I have checks for nonunique and window names with spaces that throw errors, telling the user to change the name (I should be checking for non-alphanumeric though, thanks for pointing that out!). I'd rather check and throw and error, which gives more control to the user on what they want the URL to look like. What are your thoughts?

**Comment by jcheng5** [comment]
Actually the traditional solution is URL encoding (`utils::URLencoding(x, TRUE, TRUE)`). The nice thing is that there will be no ambiguity since every input will result in a unique output. But the URL may contain, well, encoding. If it were me though, I'd much rather have the power to have whatever name appear in the UI, than to have the prettiest URL.

If you really want the best of both worlds you could modify the function API to allow the user to specify a simple id (which would become the URL param) and a human readable label separately, the way Shiny does for inputs for example. Adding options for each window would also give you a way to support things like predefined window sizes, whether to hide the browser toolbar (do browsers even let you do that anymore?), etc.

**Comment by delosh653** [comment]
It's not so much the URL being pretty, more about user control without unknown coercion. Currently, when you name a window (while following the current restrictions), you know that name will show up as given in the URL (if your window is named "Hello", your URL will be xyz/?Hello). That makes it easier to reference (since I know that it will be what I've named it and that it [hopefully] describes what the URL points to).

So with all the options, I'd rather throw an error with checks, or at least make.names() with a warning (since that is easily predictable). I would worry that by adding more options, things would get more complicated than necessary? If people clamor for it, I'd be willing to add options to control parameters and window sizing, but I'm not super convinced at the moment.

**Comment by jcheng5** [comment]
By "reference" do you mean, like, someone would type in that URL? Because my next PR was going to be letting multiple simultaneous sessions work, and for that to be possible there will need to be a huge random ID in every satellite URL...

**Comment by delosh653** [comment]
Yes, actually. At RPI, we actually do share these URLs, since we're using the campfire (https://empac.rpi.edu/program/research/campfire) and multiple computers are referencing them to get it to work. But for that PR, it makes sense to add that! I was just thinking that it would be a choice for the user to turn on, rather than the default.

**Comment by delosh653** [comment]
I'm going to merge this request, changing the URL names to what they were input to be, using make.names() for coercion of non-period/alphanumerics and throwing a warning, and merging the form to be consistent with the current version of mwshiny. Does that all sound good to you?

**Comment by delosh653** [comment]
Also, a note for myself to maybe investigate: this seems to have fixed some small but subtle problems with reactivity. Why? Who knows?

**Comment by delosh653** [comment]
Hi, I'm trying to make the edits to this pull request that I described above. Can you allow edits from maintainers on this pull request? Thanks!

**Comment by jcheng5** [comment]
Hi @delosh653, I'm not sure what you meant by "allow edits from maintainers" so I just made you a collaborator on my fork, hope that works for you. Also, sorry I didn't see your comment from Aug 15, that all sounds good.

**Comment by delosh653** [comment]
Yes that worked, thanks! I made the changes to the branch and I'm going to merge them into the master. I'm going to make a commit after to update the version and documentation, including adding you to the contributors to the package, to be submitted to CRAN. Does that work for you?

**Comment by jcheng5** [comment]
Yep!

**Pull request merged**
